import type { NewsGeneratorTheme } from "./types";

export const emeraldTheme: NewsGeneratorTheme = {
  id: "tbpn-emerald",
  pageClassName: "bg-[#05060d] tbpn-body min-h-screen text-[#f4f6ff] pb-16",
  panelClassName: "tbpn-panel text-[#e1fff5]",
  heroDescriptionClassName: "text-[#b5f9db]",
  helperTextClassName: "text-[#6fdab2]",
  labelClassName: "tbpn-label",
  chipClassName: "tbpn-chip",
  inputClassName: "bg-[#050b09] border-[#1c5f47] focus:border-[#28fcb0] text-[#e1fff5] placeholder:text-[#3f7f68]",
  imageModeActiveClassName: "border-[#2df7a7] bg-[#0c1f18] text-[#e8fff5]",
  imageModeInactiveClassName: "border-[#104b38] bg-[#050b09] text-[#7cdcb0] hover:text-white hover:border-[#1c825c]",
  glamourPublicHelperClassName: "text-[#6fdab2]",
  urlPreviewBorderClassName: "border-[#2b3a66]",
  loaderFrameClassName: "border border-[#19cc8d] shadow-[0_45px_140px_rgba(12,64,46,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#072f22] via-[#041912] to-[#010705]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#29ffb6_0%,rgba(10,44,32,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.55)] border border-[#124c38]",
  emptyFrameClassName: "border-[#1c5f47] bg-[#03120d]",
  errorPanelClassName:
    "rounded-[18px] border border-[#ff88d5] bg-[#2b0a25] text-[#ffd8f1] text-sm px-5 py-4 shadow-[0_0_25px_rgba(255,119,200,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#26ffb3] border border-[#1bd494] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#073425]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#124c38] bg-[#031a13] p-4 shadow-[0_0_35px_rgba(18,76,56,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#b5f9db]",
  nerdEmbedBorderClassName: "border-[#0f3a28]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#00b06f] text-black border-0 hover:bg-[#00dd8b] disabled:bg-[#0f3a28] disabled:text-[#76cbaa]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#6fdab2]",
  secondaryPanelClassName: "tbpn-panel text-[#9ee9c9]",
  placeholderSpinnerColor: "#26f7b0",
  renderControlsAppearance: {
    shareLabel: "Share this TBPN segment",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#050b09] text-foreground border-[#1c5f47]",
    dropzoneHoverClassName: "hover:border-[#28fcb0]",
    statusTextClassName: "text-[#d7ffef]",
    uploadingTextClassName: "text-[#6feab9]",
    errorTextClassName: "text-[#ff88d5]",
    successTextClassName: "text-[#36ffc3]",
    previewBorderClassName: "border-[#1d6f53]",
  },
  story: {
    mainInstructions:
      "Produce a high-energy trade desk segment about profile_name heading to company. Make it feel like late-night sports banter with playful speculation and quick chyron-ready bullet points. Keep each slide under 400 characters.",
    templatePic: "https://images.iwasthere.today/1758059948590-30d05235-518e-472f-b5dd-09cdeec0108d.png",
  },
  copy: {
    heroChip: "TBPN Intake",
    heroTitle: "Let's script their grand exit",
    heroDescription:
      "Spill the details—who's peacing out, where they’re landing, and which promo pic belongs on the farewell ticker.",
    nameLabel: "Star of the show",
    nameHelper: "We'll splash this name across the chyron like breaking news.",
    companyLabel: "New gig aka the destination",
    companyHelper: "Name the shiny new playground so we can hype their next chapter.",
    promptLabel: "Add insider intel (optional)",
    promptHelper: "Spill any extra tea that should make the segment juicier.",
    glamourLabel: "Choose their glamour shot",
    glamourHelper: "Upload a file or toss in a URL—whichever makes their farewell look legendary.",
    glamourPublicHelper: "Make sure the link is public so our gossip bots can fetch it.",
    glamourUrlPlaceholder: "https://example.com/their-glow-up.png",
    errorPrefix: "Our gossip hotline glitched",
    emptyStateTitle: "No segment yet",
    emptyStateDescription: 'Fill in the TBPN rundown and hit "Render the TBPN segment" to generate a preview.',
    nerdToggleOpen: "For nerds 🤓",
    nerdToggleClose: "Close the nerd notes",
    nerdDescription:
      "This TBPN generator runs on Remotion, Nano Banana and Cloudflare Workers. We gather story beats via a Postman Flow and stitch the video together in the browser before shipping it off for rendering.",
    loaderSubtitle: "🤖 *beep boop* TBPN news desk checking the wires",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a name and future employer to cue the TBPN news desk.",
    uploadInProgressError: "Hang tight—our upload gremlins are still finishing their magic.",
    missingProfileError: "Glamour shot required—upload one or drop in a URL so the tabloids have art.",
    invalidProfileUrlError: "The URL needs to start with http:// or https:// so we can fetch their glam photo.",
  },
};

export const breakingTheme: NewsGeneratorTheme = {
  id: "tbpn-breaking",
  pageClassName: "bg-[#120204] tbpn-body min-h-screen text-[#ffe9e9] pb-16",
  panelClassName: "breaking-panel text-[#ffe9e9]",
  heroDescriptionClassName: "text-[#ffb7b7]",
  helperTextClassName: "text-[#ff8585]",
  labelClassName: "breaking-label",
  chipClassName: "breaking-chip",
  inputClassName: "bg-[#1d0507] border-[#5d1515] focus:border-[#ff3a3a] text-[#ffe9e9] placeholder:text-[#7f3b3b]",
  imageModeActiveClassName: "border-[#ff3a3a] bg-[#36060a] text-white",
  imageModeInactiveClassName:
    "border-[#4f171a] bg-[#1b0506] text-[#ff9090] hover:text-white hover:border-[#ff4d4d]",
  glamourPublicHelperClassName: "text-[#ff7c7c]",
  urlPreviewBorderClassName: "border-[#5c1d1d]",
  loaderFrameClassName: "border border-[#ff3535] shadow-[0_45px_140px_rgba(110,13,22,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#46090f] via-[#230307] to-[#0b0103]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#ff4c4c_0%,rgba(110,9,18,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.6)] border border-[#5a1416]",
  emptyFrameClassName: "border-[#5f1619] bg-[#1a0406]",
  errorPanelClassName:
    "rounded-[18px] border border-[#ff5f5f] bg-[#36080a] text-[#ffdede] text-sm px-5 py-4 shadow-[0_0_25px_rgba(255,80,80,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#ffe2e2] border border-[#ff4141] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#36080a]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#5a1416] bg-[#1a0406] p-4 shadow-[0_0_35px_rgba(90,20,22,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#ffbaba]",
  nerdEmbedBorderClassName: "border-[#471013]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#ff2f45] text-white border-0 hover:bg-[#ff4c5d] disabled:bg-[#57121a] disabled:text-[#ff9aa5]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#ff8a8a]",
  secondaryPanelClassName: "breaking-panel-secondary text-[#ffd0d0]",
  placeholderSpinnerColor: "#ff3a3a",
  renderControlsAppearance: {
    buttonClassName:
      "border border-[#ff3737] bg-[linear-gradient(90deg,rgba(71,10,13,0.92),rgba(40,4,6,0.9))] shadow-[0_0_24px_rgba(255,70,70,0.18)] hover:border-[#ff5858] hover:shadow-[0_0_32px_rgba(255,90,90,0.28)]",
    contentClassName: "text-[#ffe9e9]",
    iconClassName: "h-2.5 w-2.5 rounded-full bg-[#ff4747] shadow-[0_0_12px_rgba(255,90,90,0.8)]",
    spinnerColor: "#ff5151",
    labelClassName: "tbpn-subheadline text-xs tracking-[0.32em] uppercase",
    shareLabel: "Share this bulletin",
    hoverOverlayClassName: "bg-[radial-gradient(circle_at_top,rgba(255,80,80,0.35),rgba(0,0,0,0))]",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#1a0506] text-[#ffeaea] border-[#5d1515]",
    dropzoneHoverClassName: "hover:border-[#ff3a3a]",
    statusTextClassName: "text-[#ffd1d1]",
    uploadingTextClassName: "text-[#ff8181]",
    errorTextClassName: "text-[#ff6b6b]",
    successTextClassName: "text-[#ffbaba]",
    previewBorderClassName: "border-[#5c1d1d]",
  },
  story: {
    mainInstructions:
      "Write a fiery TBPN rivalry update about profile_name making waves at company. Channel dramatic newsroom gossip with tongue-in-cheek Succession-style humor, building to a hype outro. Cap each slide at 400 characters.",
    templatePic: "https://images.iwasthere.today/tbpn-beef-settled.png",
  },
  copy: {
    heroChip: "Breaking Desk",
    heroTitle: "Log the latest beef update",
    heroDescription:
      "Drop the key facts so TBPN can announce the ceasefire. Names, new digs, and their triumphant press photo—we’ll package it for air.",
    nameLabel: "Main player",
    nameHelper: "Who’s in the spotlight? We’ll plaster their name across the lower-third.",
    companyLabel: "Where are they heading?",
    companyHelper: "Call out the next stop so viewers know where the dust is settling.",
    promptLabel: "Add producer notes (optional)",
    promptHelper: "Any spicy beats the anchors should mention? Toss them in.",
    glamourLabel: "Provide their press shot",
    glamourHelper: "Upload an image or drop a URL so we can splash their face during the announcement.",
    glamourPublicHelper: "Make sure the link is public so the control room can pull it instantly.",
    glamourUrlPlaceholder: "https://example.com/their-press-shot.png",
    errorPrefix: "Our newsroom router glitched",
    emptyStateTitle: "No bulletin yet",
    emptyStateDescription:
      'Fill out the rundown and press "Render the TBPN segment" to preview the bulletin.',
    nerdToggleOpen: "For producers 🤓",
    nerdToggleClose: "Close the producer notes",
    nerdDescription:
      "This TBPN generator still runs on Remotion, Nano Banana, and Cloudflare Workers. We wrangle story beats via a Postman Flow, composite everything in-browser, then ship it for rendering.",
    loaderSubtitle: "🛠 Control room is lining up your segment",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a name and destination to slot this into the rundown.",
    uploadInProgressError: "Hold up—the asset ingest is still finishing.",
    missingProfileError: "We need a hero image before this makes air.",
    invalidProfileUrlError: "Image URLs must start with http:// or https:// so the control room can fetch them.",
  },
};

export const cobaltTheme: NewsGeneratorTheme = {
  id: "tbpn-cobalt",
  pageClassName: "bg-[#070717] tbpn-body min-h-screen text-[#e8e6ff] pb-16",
  panelClassName: "cobalt-panel text-[#e8e6ff]",
  heroDescriptionClassName: "text-[#bcb7ff]",
  helperTextClassName: "text-[#9e97ff]",
  labelClassName: "cobalt-label",
  chipClassName: "cobalt-chip",
  inputClassName: "bg-[#0d0e26] border-[#242763] focus:border-[#5f6fff] text-[#f1f0ff] placeholder:text-[#6a6db0]",
  imageModeActiveClassName: "border-[#6a71ff] bg-[#161842] text-white",
  imageModeInactiveClassName:
    "border-[#2b2f6f] bg-[#0f1030] text-[#8d92ff] hover:text-white hover:border-[#5159ff]",
  glamourPublicHelperClassName: "text-[#8c87ff]",
  urlPreviewBorderClassName: "border-[#2f3275]",
  loaderFrameClassName: "border border-[#5b61ff] shadow-[0_45px_140px_rgba(33,36,104,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#1c1f5d] via-[#111345] to-[#070919]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#6f79ff_0%,rgba(23,28,92,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.55)] border border-[#3137a0]",
  emptyFrameClassName: "border-[#2f347a] bg-[#101236]",
  errorPanelClassName:
    "rounded-[18px] border border-[#9c6bff] bg-[#2a1c47] text-[#f1e5ff] text-sm px-5 py-4 shadow-[0_0_25px_rgba(140,90,255,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#dad8ff] border border-[#6a71ff] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#1c1f54]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#3239a4] bg-[#12143a] p-4 shadow-[0_0_35px_rgba(54,59,160,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#cbc9ff]",
  nerdEmbedBorderClassName: "border-[#252a78]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#5560ff] text-white border-0 hover:bg-[#6c76ff] disabled:bg-[#232760] disabled:text-[#9ea5ff]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#9e97ff]",
  secondaryPanelClassName: "cobalt-panel-secondary text-[#d4d2ff]",
  placeholderSpinnerColor: "#6a71ff",
  renderControlsAppearance: {
    buttonClassName:
      "border border-[#636aff] bg-[linear-gradient(90deg,rgba(42,46,120,0.92),rgba(28,30,90,0.9))] shadow-[0_0_24px_rgba(104,111,255,0.18)] hover:border-[#7a81ff] hover:shadow-[0_0_32px_rgba(116,123,255,0.28)]",
    contentClassName: "text-[#e8e6ff]",
    iconClassName: "h-2.5 w-2.5 rounded-full bg-[#7b82ff] shadow-[0_0_12px_rgba(120,128,255,0.8)]",
    spinnerColor: "#8a92ff",
    labelClassName: "tbpn-subheadline text-xs tracking-[0.32em] uppercase",
    shareLabel: "Share this personnel update",
    hoverOverlayClassName: "bg-[radial-gradient(circle_at_top,rgba(110,118,255,0.35),rgba(0,0,0,0))]",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#101236] text-[#ecebff] border-[#2d3278]",
    dropzoneHoverClassName: "hover:border-[#6a71ff]",
    statusTextClassName: "text-[#d5d3ff]",
    uploadingTextClassName: "text-[#a8a3ff]",
    errorTextClassName: "text-[#ff9bff]",
    successTextClassName: "text-[#bdb8ff]",
    previewBorderClassName: "border-[#2f3275]",
  },
  story: {
    mainInstructions:
      "Craft a neon-soaked personnel alert about profile_name being poached to company. Lean into slick corporate intrigue with confident presenter voice and concise 350-character slides.",
    templatePic: "https://images.iwasthere.today/tbpn-poached.png",
  },
  copy: {
    heroChip: "Personnel News",
    heroTitle: "Confirm the poach",
    heroDescription:
      "Lock in who just got scooped, where they’re landing, and the glamorous headshot we’ll flash on screen.",
    nameLabel: "Who’s defecting?",
    nameHelper: "We'll slot their name into the personnel ticker in blazing neon.",
    companyLabel: "New roster spot",
    companyHelper: "Call out the new home base so the audience knows who sealed the deal.",
    promptLabel: "Add front-office notes (optional)",
    promptHelper: "Any context for the poach? Bonus metrics? Drop them in for the anchors.",
    glamourLabel: "Upload their hero shot",
    glamourHelper: "Choose an image or paste a URL so we can showcase the latest recruit.",
    glamourPublicHelper: "Ensure the link is public so the graphics desk can pull it instantly.",
    glamourUrlPlaceholder: "https://example.com/their-hero-shot.png",
    errorPrefix: "Front office tablet glitched",
    emptyStateTitle: "No personnel update yet",
    emptyStateDescription:
      'Fill out the poach details and hit "Render the TBPN segment" to preview the update.',
    nerdToggleOpen: "For analysts 🤓",
    nerdToggleClose: "Close the analyst notes",
    nerdDescription:
      "Same Remotion + Nano Banana + Cloudflare stack powers this generator. Postman handles the story beats; the browser assembles the segment before render kickoff.",
    loaderSubtitle: "🎛 Graphics desk prepping the personnel slate",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a name and new team before we can announce the poach.",
    uploadInProgressError: "Hold tight—the media ingest is still working.",
    missingProfileError: "We need their hero image before we roll this on air.",
    invalidProfileUrlError:
      "Image URLs must start with http:// or https:// so the graphics desk can fetch them.",
  },
};

export const signedTheme: NewsGeneratorTheme = {
  id: "tbpn-signed",
  pageClassName: "bg-[#080821] tbpn-body min-h-screen text-[#f0efff] pb-16",
  panelClassName: "signed-panel text-[#f0efff]",
  heroDescriptionClassName: "text-[#c9c7ff]",
  helperTextClassName: "text-[#9fa0ff]",
  labelClassName: "signed-label",
  chipClassName: "signed-chip",
  inputClassName: "bg-[#0f1030] border-[#2d3278] focus:border-[#6f76ff] text-[#f3f2ff] placeholder:text-[#676bb2]",
  imageModeActiveClassName: "border-[#7279ff] bg-[#191c50] text-white",
  imageModeInactiveClassName:
    "border-[#303784] bg-[#10123a] text-[#a4a8ff] hover:text-white hover:border-[#5e66ff]",
  glamourPublicHelperClassName: "text-[#9593ff]",
  urlPreviewBorderClassName: "border-[#353a93]",
  loaderFrameClassName: "border border-[#6b72ff] shadow-[0_45px_140px_rgba(38,41,130,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#1d2062] via-[#12154b] to-[#070822]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#7f86ff_0%,rgba(30,34,120,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.55)] border border-[#353aa4]",
  emptyFrameClassName: "border-[#31368f] bg-[#11133a]",
  errorPanelClassName:
    "rounded-[18px] border border-[#a68bff] bg-[#271c4a] text-[#f4efff] text-sm px-5 py-4 shadow-[0_0_25px_rgba(152,128,255,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#dad8ff] border border-[#7a82ff] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#1c1f54]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#373ea8] bg-[#14163c] p-4 shadow-[0_0_35px_rgba(55,62,168,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#ceccff]",
  nerdEmbedBorderClassName: "border-[#272c83]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#656dff] text-white border-0 hover:bg-[#7d84ff] disabled:bg-[#2c3070] disabled:text-[#aeb2ff]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#9fa0ff]",
  secondaryPanelClassName: "signed-panel-secondary text-[#d7d6ff]",
  placeholderSpinnerColor: "#7a82ff",
  renderControlsAppearance: {
    buttonClassName:
      "border border-[#767dff] bg-[linear-gradient(90deg,rgba(39,43,122,0.92),rgba(24,27,90,0.9))] shadow-[0_0_24px_rgba(118,125,255,0.18)] hover:border-[#8e95ff] hover:shadow-[0_0_32px_rgba(142,149,255,0.28)]",
    contentClassName: "text-[#eeedff]",
    iconClassName: "h-2.5 w-2.5 rounded-full bg-[#858cff] shadow-[0_0_12px_rgba(133,140,255,0.8)]",
    spinnerColor: "#8f96ff",
    labelClassName: "tbpn-subheadline text-xs tracking-[0.32em] uppercase",
    shareLabel: "Share this signing",
    hoverOverlayClassName: "bg-[radial-gradient(circle_at_top,rgba(126,133,255,0.35),rgba(0,0,0,0))]",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#10123c] text-[#f1f0ff] border-[#2f3586]",
    dropzoneHoverClassName: "hover:border-[#7a82ff]",
    statusTextClassName: "text-[#d5d4ff]",
    uploadingTextClassName: "text-[#aba7ff]",
    errorTextClassName: "text-[#ff96e0]",
    successTextClassName: "text-[#c8c6ff]",
    previewBorderClassName: "border-[#353b96]",
  },
  story: {
    mainInstructions:
      "Report a headline-grabbing signing about profile_name joining company. Match primetime sports coverage energy, highlight contract flavor, and keep slides punchy under 360 characters.",
    templatePic: "https://images.iwasthere.today/tbpn-signed.png",
  },
  copy: {
    heroChip: "Breaking News",
    heroTitle: "Announce the latest signing",
    heroDescription:
      "Call out who just put pen to paper, where they’re reporting, and give us the face to flash during the update.",
    nameLabel: "Signed talent",
    nameHelper: "We’ll emblazon this name across the broadcast banner.",
    companyLabel: "Team or destination",
    companyHelper: "Let viewers know which roster they’ve joined.",
    promptLabel: "Add contract notes (optional)",
    promptHelper: "Drop term highlights, position changes, or other hooks for the anchors.",
    glamourLabel: "Upload their highlight shot",
    glamourHelper: "Choose an image or URL so the signing graphic pops on screen.",
    glamourPublicHelper: "Confirm the link is public so the graphics desk can grab it instantly.",
    glamourUrlPlaceholder: "https://example.com/player-shot.png",
    errorPrefix: "Signing desk router glitched",
    emptyStateTitle: "No signing queued",
    emptyStateDescription:
      'Fill in the signing details and hit "Render the TBPN segment" to preview the card.',
    nerdToggleOpen: "For scouts 🤓",
    nerdToggleClose: "Close the scout notes",
    nerdDescription:
      "Remotion, Nano Banana, and Cloudflare still power this generator. Postman feeds the story beats; the browser assembles the segment before render.",
    loaderSubtitle: "✍️ Signing desk prepping the card",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a player and destination before this hits the wire.",
    uploadInProgressError: "Hold up—the highlight upload is still going.",
    missingProfileError: "We need their highlight image before going live.",
    invalidProfileUrlError: "Image URLs must start with http:// or https:// so we can fetch them.",
  },
};

export const fundingTheme: NewsGeneratorTheme = {
  id: "tbpn-funding",
  pageClassName: "bg-[#030d0a] tbpn-body min-h-screen text-[#dfffee] pb-16",
  panelClassName: "funding-panel text-[#e1fff5]",
  heroDescriptionClassName: "text-[#b5f9db]",
  helperTextClassName: "text-[#6fdab2]",
  labelClassName: "funding-label",
  chipClassName: "funding-chip",
  inputClassName: "bg-[#04130e] border-[#0f3a28] focus:border-[#28fcb0] text-[#e1fff5] placeholder:text-[#3f7f68]",
  imageModeActiveClassName: "border-[#2df7a7] bg-[#0c1f18] text-[#e8fff5]",
  imageModeInactiveClassName:
    "border-[#104b38] bg-[#04100c] text-[#7cdcb0] hover:text-white hover:border-[#1c825c]",
  glamourPublicHelperClassName: "text-[#6fdab2]",
  urlPreviewBorderClassName: "border-[#1f5f45]",
  loaderFrameClassName: "border border-[#19cc8d] shadow-[0_45px_140px_rgba(12,64,46,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#0d3c2a] via-[#062219] to-[#010907]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#32ffbb_0%,rgba(8,52,37,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.55)] border border-[#146046]",
  emptyFrameClassName: "border-[#1c5f47] bg-[#03120d]",
  errorPanelClassName:
    "rounded-[18px] border border-[#4cffd0] bg-[#06291d] text-[#c9fff0] text-sm px-5 py-4 shadow-[0_0_25px_rgba(76,255,208,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#3cffb8] border border-[#1bd494] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#073425]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#1b5d42] bg-[#041b13] p-4 shadow-[0_0_35px_rgba(18,76,56,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#b5f9db]",
  nerdEmbedBorderClassName: "border-[#0f3a28]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#1cd493] text-black border-0 hover:bg-[#28ffb3] disabled:bg-[#0f3a28] disabled:text-[#76cbaa]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#6fdab2]",
  secondaryPanelClassName: "funding-panel-secondary text-[#bfffe9]",
  placeholderSpinnerColor: "#32ffbb",
  renderControlsAppearance: {
    buttonClassName:
      "border border-[#25f7b2] bg-[linear-gradient(90deg,rgba(12,64,46,0.92),rgba(8,38,26,0.9))] shadow-[0_0_24px_rgba(37,255,181,0.18)] hover:border-[#45ffca] hover:shadow-[0_0_32px_rgba(69,255,202,0.28)]",
    contentClassName: "text-[#dfffee]",
    iconClassName: "h-2.5 w-2.5 rounded-full bg-[#36ffc3] shadow-[0_0_12px_rgba(39,255,192,0.8)]",
    spinnerColor: "#32ffbb",
    labelClassName: "tbpn-subheadline text-xs tracking-[0.32em] uppercase",
    shareLabel: "Share this funding update",
    hoverOverlayClassName: "bg-[radial-gradient(circle_at_top,rgba(64,255,206,0.35),rgba(0,0,0,0))]",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#04130e] text-foreground border-[#0f3a28]",
    dropzoneHoverClassName: "hover:border-[#28fcb0]",
    statusTextClassName: "text-[#d7ffef]",
    uploadingTextClassName: "text-[#6feab9]",
    errorTextClassName: "text-[#ffb3e5]",
    successTextClassName: "text-[#36ffc3]",
    previewBorderClassName: "border-[#1d6f53]",
  },
  story: {
    mainInstructions:
      "Announce a funding round with profile_name and company, spotlighting lead investors and why the raise matters. Embrace upbeat business cable energy with crisp 360-character slides.",
    templatePic: "https://images.iwasthere.today/tbpn-funding-news.png",
  },
  copy: {
    heroChip: "Funding News",
    heroTitle: "Prep the headline for this raise",
    heroDescription:
      "Plug in the founder, the fresh destination, and the lead investors so TBPN can hype the round.",
    nameLabel: "Who just landed the cash?",
    nameHelper: "We'll splash their name across the ticker with a fresh funding glow.",
    companyLabel: "Who's leading the round?",
    companyHelper: "Call out the lead investor so viewers know who's backing the move.",
    promptLabel: "Add deal notes (optional)",
    promptHelper: "Share valuation highlights, fellow investors, or anything the anchors should tease.",
    glamourLabel: "Drop a hero shot",
    glamourHelper: "Upload art or paste a URL so the card features the founders on screen.",
    glamourPublicHelper: "Double-check the link is public so the graphics desk can pull it instantly.",
    glamourUrlPlaceholder: "https://example.com/founder-shot.png",
    errorPrefix: "Funding desk modem glitched",
    emptyStateTitle: "No funding card yet",
    emptyStateDescription:
      'Fill in the round, hit "Render the TBPN segment", and we’ll preview the broadcast card.',
    nerdToggleOpen: "For deal nerds 🤓",
    nerdToggleClose: "Close the deal notes",
    nerdDescription:
      "Remotion, Nano Banana, and Cloudflare still drive this flow. Postman pipes in the beats, the browser stitches the story before render kickoff.",
    loaderSubtitle: "💸 Funding desk lining up the card",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a founder and a lead investor before the card can run.",
    uploadInProgressError: "Hold tight—the hero art is still uploading.",
    missingProfileError: "We need that hero image before it goes to air.",
    invalidProfileUrlError: "Image URLs must start with http:// or https:// so we can fetch them.",
  },
};

export const profileTheme: NewsGeneratorTheme = {
  id: "tbpn-profile",
  pageClassName: "bg-[#120202] tbpn-body min-h-screen text-[#ffe9eb] pb-16",
  panelClassName: "profile-panel text-[#ffe9eb]",
  heroDescriptionClassName: "text-[#ffbdc5]",
  helperTextClassName: "text-[#ff8c98]",
  labelClassName: "profile-label",
  chipClassName: "profile-chip",
  inputClassName: "bg-[#1c0508] border-[#5d151f] focus:border-[#ff515c] text-[#ffe9eb] placeholder:text-[#7f3b40]",
  imageModeActiveClassName: "border-[#ff505d] bg-[#36060a] text-white",
  imageModeInactiveClassName:
    "border-[#4f171a] bg-[#200306] text-[#ff8f99] hover:text-white hover:border-[#ff4d4d]",
  glamourPublicHelperClassName: "text-[#ff747f]",
  urlPreviewBorderClassName: "border-[#5c1d1f]",
  loaderFrameClassName: "border border-[#ff4d5a] shadow-[0_45px_140px_rgba(110,13,22,0.55)]",
  loaderBackgroundClassName: "bg-gradient-to-br from-[#46090f] via-[#230307] to-[#0b0103]",
  loaderHighlightClassName: "bg-[radial-gradient(circle_at_top,#ff5c6b_0%,rgba(110,9,18,0)_65%)]",
  playerFrameClassName: "shadow-[0_35px_110px_rgba(0,0,0,0.6)] border border-[#5a1416]",
  emptyFrameClassName: "border-[#5f1619] bg-[#1a0406]",
  errorPanelClassName:
    "rounded-[18px] border border-[#ff7e95] bg-[#36080a] text-[#ffe0e8] text-sm px-5 py-4 shadow-[0_0_25px_rgba(255,118,149,0.35)]",
  nerdButtonClassName:
    "tbpn-subheadline text-[11px] uppercase tracking-[0.3em] text-[#ffd7dc] border border-[#ff4d5c] rounded-full px-4 py-2 transition-colors duration-200 hover:bg-[#36080a]",
  nerdPanelClassName:
    "w-full rounded-[18px] border border-[#5a1416] bg-[#1a0406] p-4 shadow-[0_0_35px_rgba(90,20,22,0.35)]",
  nerdTextClassName: "text-xs leading-6 text-[#ffc2cc]",
  nerdEmbedBorderClassName: "border-[#471013]",
  primaryButtonClassName:
    "tbpn-headline tracking-[0.22em] text-sm h-12 px-8 bg-[#ff2f45] text-white border-0 hover:bg-[#ff4c5d] disabled:bg-[#57121a] disabled:text-[#ff9aa5]",
  noDataTitleClassName: "tbpn-headline text-xl text-white",
  noDataDescriptionClassName: "mt-3 text-sm text-[#ff8a8a]",
  secondaryPanelClassName: "profile-panel-secondary text-[#ffd0d4]",
  placeholderSpinnerColor: "#ff5c6b",
  renderControlsAppearance: {
    buttonClassName:
      "border border-[#ff515f] bg-[linear-gradient(90deg,rgba(71,10,13,0.92),rgba(40,4,6,0.9))] shadow-[0_0_24px_rgba(255,70,70,0.18)] hover:border-[#ff6f79] hover:shadow-[0_0_32px_rgba(255,98,108,0.28)]",
    contentClassName: "text-[#ffe9eb]",
    iconClassName: "h-2.5 w-2.5 rounded-full bg-[#ff5f6d] shadow-[0_0_12px_rgba(255,95,109,0.8)]",
    spinnerColor: "#ff6f7d",
    labelClassName: "tbpn-subheadline text-xs tracking-[0.32em] uppercase",
    shareLabel: "Share this profile drop",
    hoverOverlayClassName: "bg-[radial-gradient(circle_at_top,rgba(255,90,104,0.35),rgba(0,0,0,0))]",
  },
  imageUploadAppearance: {
    dropzoneClassName: "bg-[#1a0506] text-[#ffeaea] border-[#5d1515]",
    dropzoneHoverClassName: "hover:border-[#ff3a3a]",
    statusTextClassName: "text-[#ffd1d1]",
    uploadingTextClassName: "text-[#ff8181]",
    errorTextClassName: "text-[#ff6b6b]",
    successTextClassName: "text-[#ffbaba]",
    previewBorderClassName: "border-[#5c1d1d]",
  },
  story: {
    mainInstructions:
      "Deliver a glam newsroom hit about profile_name debuting a new company profile picture. Celebrate the glow-up with playful fashion-desk commentary, keeping each slide under 340 characters.",
    templatePic: "https://images.iwasthere.today/tbpn-new-profile-pic.png",
  },
  copy: {
    heroChip: "Breaking News",
    heroTitle: "Drop the new profile pic",
    heroDescription:
      "Showcase the refreshed headshot and hype the update before it hits the feed.",
    nameLabel: "Who’s debuting the look?",
    nameHelper: "We’ll flash their name across the lower-third.",
    companyLabel: "Where’s it going live?",
    companyHelper: "Call out the platform or destination getting the glow-up.",
    promptLabel: "Add glam squad notes (optional)",
    promptHelper: "Mention the inspiration, photographer, or anything the anchors should tease.",
    glamourLabel: "Upload the hero shot",
    glamourHelper: "Select a file or paste a URL so we can run it on loop.",
    glamourPublicHelper: "Make sure the link is public so the newsroom can grab it instantly.",
    glamourUrlPlaceholder: "https://example.com/new-profile-pic.png",
    errorPrefix: "Photo desk modem glitched",
    emptyStateTitle: "No profile update queued",
    emptyStateDescription:
      'Fill in the details and hit "Render the TBPN segment" to preview the profile update card.',
    nerdToggleOpen: "For glam nerds 🤓",
    nerdToggleClose: "Close the glam notes",
    nerdDescription:
      "Same Remotion + Nano Banana + Cloudflare stack, now tuned for profile drops. Postman feeds the beats; the browser assembles the highlight before render.",
    loaderSubtitle: "📸 Photo desk lining up the card",
    primaryButton: "Render the TBPN segment",
    missingNameCompanyError: "We need a name and destination before this goes live.",
    uploadInProgressError: "Hold tight—the hero upload is still processing.",
    missingProfileError: "We need the hero shot before we can preview it.",
    invalidProfileUrlError: "Image URLs must start with http:// or https:// so we can fetch them.",
  },
};

export const themes = {
  emerald: emeraldTheme,
  breaking: breakingTheme,
  cobalt: cobaltTheme,
  signed: signedTheme,
  funding: fundingTheme,
  profile: profileTheme,
};

export type { NewsGeneratorTheme };
